version: '3.4'

services:

  server:
    image: goutalk
    container_name: "goutalk"
    build:
      context: .
    command: ./app -httpAddr=8000 -wsAddr=1030 -dbURI=mongodb://mongodb:27017
    ports:
      - 8000:8000
      - 1030:1030
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="goutalkmongoadmin"
      - MONGODB_PASS="supersecurepa$$w0rd"
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  chatbot:
    image: goutalk-chatbot
    container_name: "chatbot"
    build:
      context: .
    command: ./bot -dbURI=mongodb://mongodb:27017
    depends_on:
      - server